CREATE DATABASE turn;

--------------------------------------------------------------------
--------------------  TABLAS  --------------------------------------
--------------------------------------------------------------------

DROP TABLE IF EXISTS USERS_ROL;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROL;

CREATE TABLE IF NOT EXISTS USERS(
	USER_ID serial PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMEAL VARCHAR(255) UNIQUE NOT NULL,
	
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_ON TIMESTAMP,
	DELETE_ON TIMESTAMP,
	ENABLE BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE IF NOT EXISTS ROL(
	ROL_ID serial PRIMARY KEY,
	ROLNAME VARCHAR(50) UNIQUE NOT NULL,
	
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DELETE_ON TIMESTAMP,
	ENABLE BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE IF NOT EXISTS USERS_ROL (
	USER_ID INT NOT NULL,
	ROL_ID INT NOT NULL,
	
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DELETE_ON TIMESTAMP,
	ENABLE BOOLEAN NOT NULL DEFAULT TRUE,
	
	PRIMARY KEY (USER_ID, ROL_ID),
	FOREIGN KEY (ROL_ID) REFERENCES ROL (ROL_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

--------------------------------------------------------------------
--------------------  DATA  ----------------------------------------
--------------------------------------------------------------------

INSERT INTO USERS (USERNAME, LASTNAME, PASSWORD, EMEAL) VALUES ('Martin', 'Ruggeri'	, '1234', 'martinruggeri.00@gmail.com');
INSERT INTO USERS (USERNAME, LASTNAME, PASSWORD, EMEAL) VALUES ('Felpa'	, 'Sanz'	, '1234', 'felpa00@gmail.com');

INSERT INTO ROL (ROLNAME) VALUES ('customer');
INSERT INTO ROL (ROLNAME) VALUES ('admin');

INSERT INTO USERS_ROL (USER_ID, ROL_ID) VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'Martin')	, (SELECT ROL_ID FROM ROL WHERE ROLNAME = 'admin'));
INSERT INTO USERS_ROL (USER_ID, ROL_ID) VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'Felpa')	, (SELECT ROL_ID FROM ROL WHERE ROLNAME = 'customer'));
