-- CREATE DATABASE turn;

--------------------------------------------------------------------
--------------------  TABLAS  --------------------------------------
--------------------------------------------------------------------

DROP TABLE IF EXISTS TURN;
DROP TABLE IF EXISTS USERS_ROL;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROL;
DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS STATE_TURN;


CREATE TABLE IF NOT EXISTS USERS(
	USER_ID serial PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_ON TIMESTAMP
);


CREATE TABLE IF NOT EXISTS ROL(
	ROL_ID serial PRIMARY KEY,
	ROLNAME VARCHAR(50) UNIQUE NOT NULL,
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS USERS_ROL (
	USER_ID INT NOT NULL,
	ROL_ID INT NOT NULL,
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_ID, ROL_ID),
	FOREIGN KEY (ROL_ID) REFERENCES ROL (ROL_ID) ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS SCHEDULE (
	SCHEDULE_ID serial PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(250) NOT NULL,
	START_DAY DATE NOT NULL DEFAULT CURRENT_DATE,
	END_DAY DATE NOT NULL,
	START_TIME TIME NOT NULL,
	END_TIME TIME NOT NULL,
	INTERVAL_TURN INT NOT NULL,
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_ON TIMESTAMP
);


CREATE TABLE IF NOT EXISTS STATE_TURN (
	STATE_TURN_CODE VARCHAR(50) PRIMARY KEY,
	STATE_NAME VARCHAR(150) NOT NULL UNIQUE,
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_ON TIMESTAMP
);


CREATE TABLE IF NOT EXISTS TURN (
	TURN_ID serial PRIMARY KEY,
	DATE DATE NOT NULL,
	START_TIME TIME NOT NULL,
	END_TIME TIME NOT NULL,
	SCHEDULE_ID INT NOT NULL,
	STATE_TURN_CODE VARCHAR(50) NOT NULL DEFAULT 'DISP',
	USER_ID INT,
	CREATE_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_ON TIMESTAMP,
	UNIQUE (DATE, START_TIME, END_TIME, SCHEDULE_ID),
	FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (SCHEDULE_ID) ON DELETE CASCADE,
	FOREIGN KEY (STATE_TURN_CODE) REFERENCES STATE_TURN (STATE_TURN_CODE) ON DELETE SET DEFAULT,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE SET NULL
);

--------------------------------------------------------------------
--------------------  DATA  ----------------------------------------
--------------------------------------------------------------------

INSERT INTO ROL (ROLNAME) VALUES ('admin');
INSERT INTO ROL (ROLNAME) VALUES ('customer');


INSERT INTO STATE_TURN (STATE_TURN_CODE, STATE_NAME) VALUES ('DISP'		, 'Disponible');
INSERT INTO STATE_TURN (STATE_TURN_CODE, STATE_NAME) VALUES ('NO_DISP'	, 'No Disponible');
INSERT INTO STATE_TURN (STATE_TURN_CODE, STATE_NAME) VALUES ('SOLC'		, 'Solicitado');
INSERT INTO STATE_TURN (STATE_TURN_CODE, STATE_NAME) VALUES ('FINAL'	, 'Finalizado');